### ISSUE TITLE
Support includes on compile time

### ISSUE THREAD

**Issue by titpetric** [SlinSo/egon#2]
I'm splitting up a project into many files, like this:

```
./partials/head.ejs
./partials/header.ejs
./partials/foot.ejs
./partials/footer.ejs
./index.ejs
./content/setup.ejs
./content/login.ejs
./content/error.ejs
```

Using them with available functions is a bit of a hassle as I have to take care of a few horrible things to make this usable. For example, my index.ejs looks something like this:

```
<%%
import (
        "app/common"
        "app/web/templates/partials"
        "app/web/templates/content"
        "github.com/codegangsta/inject"
)
%%><%! injector inject.Injector, view common.View %><%

        injector.Invoke(partials.HeadTemplate)
        injector.Invoke(partials.HeaderTemplate)

        %><div class="container-fluid"><%

        switch {
                case view.Content == "error":
                        injector.Invoke(content.ErrorTemplate)
                        break
                case view.Content == "setup":
                        injector.Invoke(content.SetupTemplate)
                        break
                case view.Content == "login":
                        injector.Invoke(content.LoginTemplate)
                        break
        }

        %></div><%

        injector.Invoke(partials.FooterTemplate)
        injector.Invoke(partials.FootTemplate)
%>
```

The problems with this approach:
1. I have to define extra imports
2. I have to use injection in the template

One possible fix would be to add an option to compile everything into one golang file, so I could skip additional imports (solves 1/2 of the problem). The name generation for functions is good enough to prevent clashes.

I suggest to add an include statement, that would "copy-paste" the file contents on compile time into the main source file. From EJS:

> Includes are relative to the template with the include call. For example if you have "./views/users.ejs" and "./views/user/show.ejs" you would use <%- include('user/show'); %>.

**Comment by slinso** [comment]
Hi @titpetric,

just invoke the function of the subtemplate. that way we don't need a include feature.
